/**
 * V4 (ADR 0031) — Dynamic context assembly.
 *
 * Instead of a static system prompt, each agent run assembles a
 * {@link ContextBundle}: a structured, token-budget-aware selection of the
 * live scene snapshot, perf data, relevant past session outcomes, matching
 * playbooks, and any error context that triggered the run. The
 * `buildTriangleSystemPrompt` refactor turns this bundle into the per-run
 * system prompt, prioritising error context > scene snapshot > playbook >
 * history and truncating gracefully within the budget.
 *
 * Replaces V0's placeholder `ContextBundle` (`{ summary; tokenEstimate? }`);
 * those two fields remain for back-compat so existing callers (the automation
 * engine's `{ summary }` shape) keep compiling.
 */
import type { PerformanceSnapshot, SceneSummary } from './preview.js';

/**
 * A recalled past session outcome relevant to the current run. Sourced from
 * `ProjectMemory.recall` (TF-IDF over session transcripts + user notes) and
 * bounded by the token budget.
 */
export interface RecallSessionOutcome {
  /** The session/run id. */
  id: string;
  /** The user prompt that started the run. */
  prompt: string;
  /** Terminal status (`completed` | `error` | `cancelled` | …). */
  status: string;
  /** One-line outcome summary (e.g. "completed, 2 writes, verification passed"). */
  outcome: string;
  /** Epoch ms the run started. */
  ts: number;
  /** TF-IDF relevance score to the query, when known (higher = more relevant). */
  score?: number;
}

/** A user-authored project note indexed by the memory store. */
export interface MemoryNote {
  /** Stable id (generated by the store). */
  id: string;
  /** The note body (project-scoped guidance, e.g. "always use 16-bit precision"). */
  text: string;
  /** Epoch ms the note was created. */
  createdAt: number;
  /** Epoch ms the note was last edited, when applicable. */
  updatedAt?: number;
}

/** A memory entry returned by `recall` / `search` (notes + session outcomes). */
export interface MemoryEntry {
  /** Stable id of the underlying note or session. */
  id: string;
  /** `note` (user-authored) or `session` (past run outcome). */
  kind: 'note' | 'session';
  /** The text content indexed for recall. */
  text: string;
  /** Epoch ms. */
  ts: number;
  /** TF-IDF relevance score to the query, when known. */
  score?: number;
}

/** Error context attached when a run is triggered by a preview error. */
export interface ErrorContext {
  /** The error message. */
  message: string;
  /** Source path / shader name, when known. */
  source?: string;
  /** Diagnostics lines (compiler errors, stack frames, …). */
  diagnostics?: string[];
}

/** A matching playbook promoted into the run's context. */
export interface ContextPlaybook {
  /** Stable playbook id (built-ins use the `builtin-` prefix). */
  id: string;
  /** Human-readable name. */
  name: string;
  /** The plan/prompt body to inject. */
  plan: string;
  /** Keywords that caused the match, for transparency. */
  matchedOn?: string[];
}

/**
 * The structured context assembled per run. V4 populates this from
 * `ProjectMemory.recall` + the live scene/perf snapshot (via `PreviewBridge`)
 * + matching playbooks; `buildTriangleSystemPrompt` renders it into the
 * per-run system prompt within {@link ContextBundle.tokenBudget}.
 */
export interface ContextBundle {
  /** Human-readable summary of attached context (back-compat with V0). */
  summary: string;
  /** Token estimate of the assembled context, when known (back-compat). */
  tokenEstimate?: number;
  /** Live scene graph snapshot, when the preview was open at assembly time. */
  scene?: SceneSummary;
  /** Live performance snapshot, when available. */
  perf?: PerformanceSnapshot;
  /** Relevant past session outcomes (TF-IDF recalled, budget-bounded). */
  recentSessions?: RecallSessionOutcome[];
  /** Matching playbooks promoted into the prompt. */
  playbooks?: ContextPlaybook[];
  /** User notes recalled as relevant to the run. */
  notes?: MemoryNote[];
  /** Error context when the run was triggered by a preview error. */
  error?: ErrorContext;
  /** The token budget the assembled prompt must stay within. */
  tokenBudget?: number;
}

/**
 * A versioned, structured playbook. V4 promotes the built-in playbooks
 * (`templates/playbooks/*.json`) and `docs/PROMPTING.md` guidance into this
 * shape so the memory system can load matching playbooks into context. The
 * built-in `Automation` JSON files are the existing trigger/scope surface;
 * this type carries the prompt-body + keyword facets the context pipeline
 * matches on.
 */
export interface Playbook {
  /** Stable id (built-ins use the `builtin-` prefix). */
  id: string;
  /** Human-readable name. */
  name: string;
  /** Short description. */
  description: string;
  /** The plan/prompt body handed to the agent when this playbook matches. */
  plan: string;
  /** Keywords that trigger a match against the run prompt (lower-cased). */
  keywords: string[];
  /** Schema version, so the loader can evolve the shape safely. */
  version: number;
  /** True for the built-in playbooks shipped with the app. */
  builtIn?: boolean;
}
